CREATE TABLE requests (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    age INT NOT NULL,
    phone VARCHAR(11) NOT NULL,
    attendance ENUM('FULL-TIME', 'PART-TIME') NOT NULL,
    name VARCHAR(255),
    comment VARCHAR(255)
);
